[workspace]
members = [
    "proxmox-nftables",
    "proxmox-firewall",
]
resolver = "3"

[workspace.dependencies]
proxmox-network-types = { version = "0.1" }
proxmox-ve-config = { version = "0.4.6" }
